version: "3.7"


networks:
  luminos_network:  
    external: true
        
services:

  browser_file:
    image: filebrowser/filebrowser
    restart: always
    networks:
      - luminos_network
      - default
    volumes:
      - luminos_master:/srv
    deploy:
      replicas: 1
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=luminos_network"

        - "traefik.http.routers.luminos-browser.rule=Host(`browser.lvxnight.com`)"
        - "traefik.http.routers.luminos-browser.service=luminos-browser-svc"
        - "traefik.http.routers.luminos-browser.entrypoints=web-secure"
        - "traefik.http.routers.luminos-browser.tls.certresolver=certificato"
        - "traefik.http.services.luminos-browser-svc.loadbalancer.server.port=80"

    
    
  minio:
    image: minio/minio:latest
    command: server /data --console-address ":3000"
    restart: always
    networks:
      - luminos_network
      - default
    environment:
      - MINIO_ROOT_USER=luminos
      - MINIO_ROOT_PASSWORD=fb46b3f4-3cae-4506-8aca-c13adb98990b
      - MINIO_BROWSER_REDIRECT_URL=https://dashboard.cdn.lvxnight.com
      - MINIO_SERVER_URL=https://cdn.lvxnight.com
    volumes:
      - luminos_cdn:/data
    deploy:
      replicas: 1
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=luminos_network"

        - "traefik.http.routers.luminos-cdn.rule=Host(`cdn.lvxnight.com`)"
        - "traefik.http.routers.luminos-cdn.service=luminos-cdn-svc"
        - "traefik.http.routers.luminos-cdn.entrypoints=web-secure"
        - "traefik.http.routers.luminos-cdn.tls.certresolver=certificato"
        - "traefik.http.services.luminos-cdn-svc.loadbalancer.server.port=9000"

        - "traefik.http.routers.luminos-dashboard-cdn.rule=Host(`dashboard.cdn.lvxnight.com`)"
        - "traefik.http.routers.luminos-dashboard-cdn.service=luminos-dashboard-cdn-svc"
        - "traefik.http.routers.luminos-dashboard-cdn.entrypoints=web-secure"
        - "traefik.http.routers.luminos-dashboard-cdn.tls.certresolver=certificato"
        - "traefik.http.services.luminos-dashboard-cdn-svc.loadbalancer.server.port=3000"

volumes:
  luminos_cdn:
    driver_opts:
      type: "nfs"
      o: "addr=188.165.205.181,rw,noatime,rsize=8192,wsize=8192,tcp,timeo=14"
      device: ":/var/nfs/general/cdn"
  luminos_master:
    external: true
      




